catalog:
  "@eslint/eslintrc": "^3.2.0"
  "@eslint/js": "^9.18.0"
  "@nestjs/cli": "^11.0.0"
  "@nestjs/common": "^11.0.1"
  "@nestjs/core": "^11.0.1"
  "@nestjs/platform-ws": "^11.0.1"
  "@nestjs/swagger": "^11.2.6"
  "@nestjs/websockets": "^11.0.1"
  "@oclif/core": "^4.2.8"
  "@radix-ui/react-slot": "^1.2.4"
  "@rsbuild/core": "^1.1.9"
  "@rsbuild/plugin-react": "^1.1.0"
  "@types/better-sqlite3": "^7.6.13"
  "@types/node": "^22.10.7"
  "@types/react": "^19.0.0"
  "@types/react-dom": "^19.0.0"
  "better-sqlite3": "^11.8.1"
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "eslint": "^9.18.0"
  "eslint-config-prettier": "^10.0.1"
  "eslint-plugin-prettier": "^5.2.2"
  "ink": "^6.6.0"
  "lucide-react": "^0.563.0"
  "openapi-fetch": "^0.15.0"
  "openapi-typescript": "^7.10.1"
  "prettier": "^3.4.2"
  "react": "19.2.3"
  "react-dom": "19.2.3"
  "tailwind-merge": "^3.4.0"
  "tailwindcss": "^4"
  "ts-node": "^10.9.2"
  "tsc-alias": "^1.8.16"
  "typescript": "^5.7.3"
  "typescript-eslint": "^8.20.0"
  "xstate": "^5"
packages:
  - common/server
  - common/nestjs-core
  - common/nestjs-debate
  - common/debate-machine
  - common/debate-web
  - common/cli-shared
  - common/node-shared
  - common/playwright
  - common/cli
  - common/cli-plugin-debate
  - common/cli-plugin-docs
  - common/cli-plugin-dashboard
  - common/cli-plugin-relay
  - common/nestjs-dashboard
  - common/dashboard-web
  - common/workflow-engine
  - common/workflow-dashboard
  - common/config-core
  - common/config
  - common/cli-plugin-config
  - common/cli-plugin-server
  - common/cli-plugin-demo-workflow
  - common/cli-plugin-test
  - common/workspace-memory
  - common/nestjs-workspace-memory
  - common/cli-plugin-workspace

onlyBuiltDependencies:
  - "@nestjs/core"
  - "better-sqlite3"
