/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["DebateController_healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List debates with optional filtering */
        get: operations["DebateController_listDebates"];
        put?: never;
        /** Create a new debate with initial MOTION argument */
        post: operations["DebateController_createDebate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get debate with motion and arguments */
        get: operations["DebateController_getDebate"];
        put?: never;
        post?: never;
        /** Delete a debate and all its arguments */
        delete: operations["DebateController_deleteDebate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debates/{id}/arguments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a CLAIM argument */
        post: operations["DebateController_submitArgument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debates/{id}/appeal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an APPEAL */
        post: operations["DebateController_submitAppeal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debates/{id}/resolution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request debate completion (RESOLUTION) */
        post: operations["DebateController_submitResolution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debates/{id}/intervention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an INTERVENTION (arbitrator only) */
        post: operations["DebateController_submitIntervention"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debates/{id}/ruling": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a RULING (arbitrator only) */
        post: operations["DebateController_submitRuling"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debates/{id}/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Long-poll for new arguments */
        get: operations["DebateController_poll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PollArgumentDataDto: {
            id: string;
            seq: number;
            /** @enum {string} */
            type: "MOTION" | "CLAIM" | "APPEAL" | "RULING" | "INTERVENTION" | "RESOLUTION";
            /** @enum {string} */
            role: "proposer" | "opponent" | "arbitrator";
            parent_id: string | null;
            content: string;
            created_at: string;
        };
        PollResultNewDataDto: {
            /** @example true */
            has_new_argument: boolean;
            action: string;
            debate_state: string;
            argument: components["schemas"]["PollArgumentDataDto"];
        };
        PollResultNewResponseDto: {
            /** @example true */
            success: boolean;
            data: components["schemas"]["PollResultNewDataDto"];
        };
        PollResultNoNewDataDto: {
            /** @example false */
            has_new_argument: boolean;
            debate_id: string;
            last_seen_seq: number;
        };
        PollResultNoNewResponseDto: {
            /** @example true */
            success: boolean;
            data: components["schemas"]["PollResultNoNewDataDto"];
        };
        ErrorDetailDto: {
            /**
             * @description Error code (NOT_FOUND, INVALID_INPUT, ACTION_NOT_ALLOWED, etc.)
             * @example VALIDATION_ERROR
             */
            code: string;
            /** @example Invalid debate_id format */
            message: string;
            /** @description Suggested action to fix the error */
            suggestion?: string;
            /** @description Current debate state (present in ACTION_NOT_ALLOWED errors) */
            current_state?: string;
            /** @description Roles allowed for this action (present in ACTION_NOT_ALLOWED errors) */
            allowed_roles?: string[];
        };
        ErrorResponseDto: {
            /** @example false */
            success: boolean;
            error: components["schemas"]["ErrorDetailDto"];
        };
        DebateDto: {
            /** @description UUID */
            id: string;
            title: string;
            /** @enum {string} */
            debate_type: "coding_plan_debate" | "general_debate";
            /** @enum {string} */
            state: "AWAITING_OPPONENT" | "AWAITING_PROPOSER" | "AWAITING_ARBITRATOR" | "INTERVENTION_PENDING" | "CLOSED";
            /** @description ISO datetime */
            created_at: string;
            /** @description ISO datetime */
            updated_at: string;
        };
        ListDebatesDataDto: {
            debates: components["schemas"]["DebateDto"][];
            total: number;
        };
        ListDebatesResponseDto: {
            /** @example true */
            success: boolean;
            data: components["schemas"]["ListDebatesDataDto"];
        };
        CreateDebateBodyDto: {
            debate_id: string;
            title: string;
            /** @enum {string} */
            debate_type: "coding_plan_debate" | "general_debate";
            motion_content: string;
            client_request_id: string;
        };
        ArgumentDto: {
            id: string;
            debate_id: string;
            parent_id: string | null;
            /** @enum {string} */
            type: "MOTION" | "CLAIM" | "APPEAL" | "RULING" | "INTERVENTION" | "RESOLUTION";
            /** @enum {string} */
            role: "proposer" | "opponent" | "arbitrator";
            content: string;
            client_request_id: string | null;
            seq: number;
            /** @description ISO datetime */
            created_at: string;
        };
        WriteResultDataDto: {
            debate: components["schemas"]["DebateDto"];
            argument: components["schemas"]["ArgumentDto"];
        };
        WriteResultResponseDto: {
            /** @example true */
            success: boolean;
            data: components["schemas"]["WriteResultDataDto"];
        };
        GetDebateDataDto: {
            debate: components["schemas"]["DebateDto"];
            motion: components["schemas"]["ArgumentDto"] | null;
            arguments: components["schemas"]["ArgumentDto"][];
        };
        GetDebateResponseDto: {
            /** @example true */
            success: boolean;
            data: components["schemas"]["GetDebateDataDto"];
        };
        SubmitArgumentBodyDto: {
            /** @enum {string} */
            role: "proposer" | "opponent";
            target_id: string;
            content: string;
            client_request_id: string;
        };
        SubmitAppealBodyDto: {
            target_id: string;
            content: string;
            client_request_id: string;
        };
        RequestCompletionBodyDto: {
            target_id: string;
            content: string;
            client_request_id: string;
        };
        SubmitInterventionBodyDto: {
            content?: string;
            client_request_id?: string;
        };
        SubmitRulingBodyDto: {
            content: string;
            close?: boolean;
            client_request_id?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    DebateController_healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DebateController_listDebates: {
        parameters: {
            query?: {
                /** @description Filter by debate state */
                state?: string;
                /** @description Max results to return */
                limit?: number;
                /** @description Pagination offset */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of debates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDebatesResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    DebateController_createDebate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDebateBodyDto"];
            };
        };
        responses: {
            /** @description Debate created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResultResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    DebateController_getDebate: {
        parameters: {
            query?: {
                /** @description Max arguments to return */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Debate UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Debate detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetDebateResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    DebateController_deleteDebate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Debate UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Debate deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    DebateController_submitArgument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Debate UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitArgumentBodyDto"];
            };
        };
        responses: {
            /** @description Argument submitted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResultResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Action not allowed in current state */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    DebateController_submitAppeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Debate UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAppealBodyDto"];
            };
        };
        responses: {
            /** @description Appeal submitted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResultResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Action not allowed in current state */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    DebateController_submitResolution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Debate UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCompletionBodyDto"];
            };
        };
        responses: {
            /** @description Resolution submitted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResultResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Action not allowed in current state */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    DebateController_submitIntervention: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Debate UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitInterventionBodyDto"];
            };
        };
        responses: {
            /** @description Intervention submitted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResultResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Action not allowed in current state */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    DebateController_submitRuling: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Debate UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRulingBodyDto"];
            };
        };
        responses: {
            /** @description Ruling submitted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResultResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Action not allowed in current state */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    DebateController_poll: {
        parameters: {
            query: {
                /** @description Last seen argument UUID */
                argument_id?: string;
                role: "proposer" | "opponent";
            };
            header?: never;
            path: {
                /** @description Debate UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Poll result — new argument or timeout */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollResultNewResponseDto"] | components["schemas"]["PollResultNoNewResponseDto"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
}
