packages:
  - nab/cli/foo
  - common/server
  - common/nestjs-debate
  - common/debate-machine
  - common/debate-web
  - common/cli-shared
  - common/playwright
  - common/cli
  - common/cli-plugin-debate
  - common/cli-plugin-docs
  - common/cli-plugin-dashboard
  - common/cli-plugin-relay
  - common/workflow-engine
  - common/workflow-dashboard
  - common/cli-plugin-demo-workflow

onlyBuiltDependencies:
  - "@nestjs/core"
  - "better-sqlite3"